### ISSUE TITLE
#1 Kakao UserInfo를 못 불러오는 현상

### ISSUE THREAD

**Issue by howooyeon** [howooyeon/TravelAlone#29]
## 어떤 버그인가요?

> Home_Activity에서 Kakao 로그인한 UserInfo를 못 불러오는 버그

## 어떤 상황에서 발생한 버그인가요?

> Given 
* 사용자가 Firebase 또는 Kakao 로그인을 시도합니다.
* Firebase 로그인 시에는 사용자 정보에 따라 tripdate를 가져오려 합니다.
* Kakao 로그인 시에는 사용자 정보를 가져와서, Firebase에 사용자 이메일이 있는지 확인 후 tripdate를 가져오려 합니다.

> When 

**Firebase 사용자 정보 또는 Kakao 사용자 정보를 통해 Firestore에서 tripdate를 조회할 때, 아래와 같은 상황에서 에러가 발생**
- Firebase 사용자 인증이 되어 있지 않은 경우
- Kakao 사용자 정보가 올바르지 않거나 Firebase에 해당 사용자의 이메일이 없는 경우
- Firestore에서 tripdate 문서가 없거나 유효하지 않은 경우

> Then
* Firebase 인증 실패 시, "사용자가 로그인되어 있지 않습니다."라는 메시지 표시
* Kakao 사용자 정보가 없거나 문제가 발생하면, "사용자 정보 요청 실패"라는 메시지 표시
* Firestore에서 tripdate 문서를 가져오는 데 실패하거나 유효한 문서를 찾지 못하면, "유효한 일정이 없습니다."라는 메시지 표시

## 예상 결과

> 홈화면에서 여행 추가 가능

**Comment by daeun-han** [comment]
확인했습니다. 수고하셨습니다!!👏
